version: "3"
services:
  xui:
    build: 
      context: .
      dockerfile: dockerfile
    # Ports removed to let Coolify's Proxy (Traefik) handle it via port 80
    volumes:
      - xui_data:/home/xui
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  xui_data:
  mysql_data:
