version: "3"
services:
  xui:
    build: 
      context: .
      dockerfile: dockerfile
    # Let Coolify's proxy handle the external traffic
    volumes:
      - xui_data:/home/xui
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  xui_data:
  mysql_data:
